namespace CpymoEditor.Core.Projects;

public static class ProjectClassifier
{
    private const int YkmDebugRejectionThreshold = 3;

    public static ProjectClassificationResult Classify(string projectDirectory)
    {
        if (!Directory.Exists(projectDirectory))
        {
            return RejectUnknown("Project directory does not exist.");
        }

        if (ContainsYkmSource(projectDirectory))
        {
            return new ProjectClassificationResult(ProjectKind.YkmSource, CanOpen: true, Array.Empty<string>());
        }

        if (LooksLikeYkmCompiledProduct(projectDirectory))
        {
            return new ProjectClassificationResult(
                ProjectKind.RejectedYkmCompiledProduct,
                CanOpen: false,
                new[] { "This project appears to be generated by YukimiScript and cannot be safely edited as source." });
        }

        if (ContainsNativePymoProject(projectDirectory))
        {
            return new ProjectClassificationResult(ProjectKind.NativePymo, CanOpen: true, Array.Empty<string>());
        }

        return RejectUnknown("No supported YKM source files or native PyMO project files were found.");
    }

    private static bool ContainsYkmSource(string projectDirectory)
    {
        return Directory.EnumerateFiles(projectDirectory, "*.ykm", SearchOption.AllDirectories).Any();
    }

    private static bool ContainsNativePymoProject(string projectDirectory)
    {
        string gameConfig = Path.Combine(projectDirectory, "gameconfig.txt");
        string scriptDirectory = Path.Combine(projectDirectory, "script");

        return File.Exists(gameConfig)
            && Directory.Exists(scriptDirectory)
            && Directory.EnumerateFiles(scriptDirectory, "*.txt", SearchOption.AllDirectories).Any();
    }

    private static bool LooksLikeYkmCompiledProduct(string projectDirectory)
    {
        string scriptDirectory = Path.Combine(projectDirectory, "script");
        if (!Directory.Exists(scriptDirectory))
        {
            return false;
        }

        foreach (string scriptFile in Directory.EnumerateFiles(scriptDirectory, "*.txt", SearchOption.AllDirectories))
        {
            int debugLines = 0;
            foreach (string line in File.ReadLines(scriptFile))
            {
                if (line.StartsWith(";YKMDBG;", StringComparison.Ordinal))
                {
                    debugLines++;
                    if (debugLines >= YkmDebugRejectionThreshold)
                    {
                        return true;
                    }
                }
            }
        }

        return false;
    }

    private static ProjectClassificationResult RejectUnknown(string reason)
    {
        return new ProjectClassificationResult(ProjectKind.Unknown, CanOpen: false, new[] { reason });
    }
}
